package java.com.yh.panel;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import main.java.com.yh.listener.MyKeyListener;
import main.java.com.yh.listener.MyMouseListener;

import javax.swing.*;
import java.awt.*;

public class MyPanel {
    private JPanel outPanel;
    private JTextArea sqlArea;
    private JTextField dslField;
    private JScrollPane scroll;


    public MyPanel() {
        installListeners();
    }

    //添加监听事件
    private void installListeners() {
        MyMouseListener mouseListener = new MyMouseListener(scroll, dslField);
        MyKeyListener keyListener = new MyKeyListener(sqlArea, dslField);
        scroll.addMouseListener(mouseListener);
        dslField.addMouseListener(mouseListener);
        dslField.addKeyListener(keyListener);
    }

    public JPanel getOutPanel() {
        return outPanel;
    }


    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        return new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        outPanel = new JPanel();
        outPanel.setLayout(new GridLayoutManager(2, 1, new Insets(0, 0, 0, 0), -1, -1));
        outPanel.setAutoscrolls(true);
        outPanel.setMinimumSize(new Dimension(200, 70));
        outPanel.setPreferredSize(new Dimension(400, 100));
        scroll = new JScrollPane();
        scroll.setHorizontalScrollBarPolicy(32);
        scroll.setVerticalScrollBarPolicy(22);
        outPanel.add(scroll, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        sqlArea = new JTextArea();
        Font sqlAreaFont = this.$$$getFont$$$("Consolas", Font.PLAIN, 14, sqlArea.getFont());
        if (sqlAreaFont != null) sqlArea.setFont(sqlAreaFont);
        sqlArea.setLineWrap(true);
        sqlArea.setToolTipText("输入sql");
        scroll.setViewportView(sqlArea);
        dslField = new JTextField();
        Font dslFieldFont = this.$$$getFont$$$("Courier New", Font.PLAIN, 16, dslField.getFont());
        if (dslFieldFont != null) dslField.setFont(dslFieldFont);
        dslField.setToolTipText("输入dsl");
        outPanel.add(dslField, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return outPanel;
    }
}
